name: ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: mkn
      run: |
        rm -rf tests/{gtest,gmock}
        curl -Lo mkn https://github.com/mkn/mkn/releases/download/latest/mkn_nix
        chmod +x mkn
        KLOG=3 ./mkn build run -dtOp test,bench -a "-std=c++11 -fPIC -Wno-gnu-zero-variadic-macro-arguments" -W 9 -l -pthread

